version: "3.8"

services:
  php-container:
    build:
      context: ./php-container
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - .env
    restart: always
    volumes:
      - ./php-container:/app 
    command: php -S 0.0.0.0:8083 -t /app router.php

#  java-container:
#    build:
#      context: ./java-container 
#      dockerfile: Dockerfile
#    ports:
#      - "8084:8084"
#    env_file:
#      - .env
#    restart: always
#    command: java -jar app.jar
#
#  go-container:
#    build:
#      context: ./go-container 
#      dockerfile: Dockerfile
#    ports:
#      - "8085:8085"
#    env_file:
#      - .env
#    restart: always
#    command: ./app

